// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50hsCujOe340dKyGdPqF6uO5FRCokxEc',
    appId: '1:10619126838:web:a745886e38a19e85ec0497',
    messagingSenderId: '10619126838',
    projectId: 'bcdx-alpaca',
    authDomain: 'bcdx-alpaca.firebaseapp.com',
    storageBucket: 'bcdx-alpaca.appspot.com',
    measurementId: 'G-NCD9E0CVC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnBvoB9x-xEBj6033szPAoittB6JR3Yg',
    appId: '1:10619126838:android:723f369a16366ff0ec0497',
    messagingSenderId: '10619126838',
    projectId: 'bcdx-alpaca',
    storageBucket: 'bcdx-alpaca.appspot.com',
  );
}
